show databases;
use basicPAS;
show tables;
select * from product;
select * from to_products;
select * from users;
select * from workers;
select * from admin;
select * from orders;
select * from status_order;